import axios from "axios";

const BACKEND_URL =
  "https://expense-tracker-app-51621-default-rtdb.firebaseio.com";

export async function storeExpense(expenseData) {
  const response = await axios.post(BACKEND_URL + "/expenses.json", expenseData);
  const id = response.data.name; //.name property holds the autogenerated "id" from firebase
  return id;
}

export async function fetchExpenses() {
  const response = await axios.get(BACKEND_URL + "/expenses.json");

  const expenses = [];

  console.log("Response Data:" + response.data)

  for (const key in response.data) {
    //axios gives us a data property on the const response object which holds the actual data that was sent back by the server
    const expenseObj = {
      id: key, 
      amount: response.data[key].amount, 
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }
  return expenses;
}

export function updateExpense(id, expenseData) {
  return axios.put(BACKEND_URL + `/expenses/${id}.json`, expenseData)
}

export function deleteExpense(id) {
  return axios.delete(BACKEND_URL + `/expenses/${id}.json`);
}     
